apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-frontend
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: 564398348890.dkr.ecr.us-east-1.amazonaws.com/wisecow:latest
        ports:
        - containerPort: 4499
        readinessProbe:
          tcpSocket:
            port: 4499
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4499
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 4499 # Container port
  type: LoadBalancer  # Use ClusterIP if you only want internal access
